[rework] Make sure trailing space removal is counted as formatting
revelc/formatter-maven-plugin pull request #556
Opened 2022-01-03 23:58 UTC by hazendaz

2022-01-05 20:29 UTC, ctubbsii requested changes
Good idea. I noticed that whitespace trim would only work on files that needed to be formatted for another reason. Does this fix that?
Also, I think this might have an impact on how the cache works. Does the "already formatted" cache entry get added before or after the whitespace is trimmed?

2022-01-05 20:29 UTC, ctubbsii commented on CHANGELOG.md
> +- Move whitespace trim to ensure its counted in formatting stats
```suggestion
- Move whitespace trim to ensure it's counted in formatting stats
```

2022-01-05 20:29 UTC, ctubbsii commented on src/main/java/net/revelc/code/formatter/FormatterMojo.java
> +                }
Replace 5 lines with 1.

```suggestion
                result = originalCode.equals(formattedCode) ? Result.SKIPPED : Result.SUCCESS;
```

2022-01-05 20:29 UTC, ctubbsii commented
I'm also in favor of making whitespace trim default to true, but it seems like a separate (trivial) issue.

2022-01-06 03:22 UTC, hazendaz commented
@ctubbsii I'll come back to this in a day or two and review further comments you have made as a few of those need looked at more closely.  For items to address, will take care of those and if any thing else needs done will likely do on separate pull request as this was more isolated (assuming specific concerns don't require more to this one).

2022-01-06 03:26 UTC, hazendaz commented
@ctubbsii Oh and jsoup is getting things done, they fixed a major bug affecting us, fixed a few other trivial ones, and looking at a few PRs I have as well as trying to track down some issues.  So I think we will wait overall until they get a release before we push out this Eclipse set.  So Maybe end of the month or so.  In meantime, I've been doing a lot of testing which resulted in this and probably few others as I'm trying to help them figure out the html problems.  Thanks.

2022-01-08 20:22 UTC, hazendaz commented
> I'm also in favor of making whitespace trim default to true, but it seems like a separate (trivial) issue.

Yes, will be separate PR, wanted to bring it up on where my thinking was.

2022-01-08 20:22 UTC, hazendaz commented
> ticed that whitespace trim would only work on files that needed to be formatted for another reason. Does

Yes this fixes this specific issue.

2022-01-08 20:23 UTC, hazendaz commented
> Also, I think this might have an impact on how the cache works. Does the "already formatted" cache entry get added before or after the whitespace is trimmed?

The cache write occurs just after.  Both the original and this would both write cache properly.

2022-01-08 20:25 UTC, hazendaz commented
Merging this now as 2 minor coding suggestions applied.  Will bring in default change after this with changelog on that as well.  That will just leave us with an outstanding I noted here that are tests are so direct we don't notice full formatting so we need integration tests.  I'll look at our existing issues and see if that was evern noted, it not I'll make note of it.  That is also something I probably can mostly tackle.  I'm familiar enough on using invoker plugin for integration tests on maven plugin and how to use groovy to verify things.  Bulk of that should be easy here since its checking hashes for us.

2022-01-08 20:25 UTC, merged